{
 "title": "ATV Performance",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ATV",
    "label": "ATV",
    "query": "SELECT DISTINCT(deviceName) FROM ATVstats;"
   },
   {
    "name": "RPL",
    "query": "select distinct(RPL) from ATVstats;"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU System Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuSys AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU User Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuUser AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Pogo Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuPogoPct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV)\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU ArlasUsage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuApct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 5min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL5 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 10min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL10 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "CPU Load 15min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  cpuL15 AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "ATV Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ATV Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  temperature AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MemFree",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memFree AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "MemUsage Pogo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memPogo AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "MemUsage Attlas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  memAtlas AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "DiskUsage System %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  diskSysPct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  },
  {
   "title": "DiskUsage Data %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(timestamp,$__interval,NULL),\n  diskDataPct AS metric,\n  deviceName AS \"deviceName\"\nFROM ATVstats\nWHERE\n  $__timeFilter(timestamp) AND\n  deviceName IN ($ATV) AND\n  RPL = $RPL\nGROUP BY 1,2\nORDER BY $__timeGroup(timestamp,$__interval,NULL)"
    }
   ]
  }
 ]
}