{
 "title": "ATVdetails overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ATV general",
   "type": "table",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(arch,'no_data') as 'Architecture',\nifnull(productmodel,'nodata') as 'Productmodel',\nifnull(atlasSh,'no_data') as 'atlas.sh',\nifnull(whversion,'no_data') as 'wh_sender',\nifnull(monitor,'no_data') as 'monitor',\nifnull(playstoreenabled, 'no_data') as 'Playstore Update',\nifnull(proxyinfo, 'no_data') as 'Proxy',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY arch,productmodel,atlasSh,whversion,monitor\n"
    }
   ]
  },
  {
   "title": "Magisk / modules",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(magisk,'no_data') as 'Magisk',\nifnull(magisk_modules,'no_data') as 'Modules loaded',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY magisk, magisk_modules\n"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 10, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(pogo,'no_data') as 'PoGo',\nifnull(atlas,'no_data') as 'Atlas',\nifnull(atlasSh,'no_data') as 'atlas.sh',\nifnull(55atlas,'no_data') as '55atlas',\nifnull(49atlas,'no_data') as '49atlas',\nifnull(whversion,'no_data') as 'wh_sender',\nifnull(monitor,'no_data') as 'monitor',\nifnull(playstore,'no_data') as 'playstore Ver',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY pogo,atlas\n"
    }
   ]
  },
  {
   "title": "Atlas settings",
   "type": "table",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\nifnull(rdmUrl, 'no_data') as 'rdmUrl',\nifnull(authBearer, 'no_data') as 'authBearer',\nifnull(token, 'no_data') as 'deviceAuthToken',\nifnull(email, 'no_data') as 'email',\nifnull(onBoot, 'no_data') as 'runOnBoot',\ncount(deviceName) as '#devices'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\nGROUP BY rdmUrl,authBearer,token,email,onBoot"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\nmin(temperature) as 'minTemp',\navg(temperature) as 'avgTemp',\nmax(temperature) as 'maxTemp'\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day"
    }
   ]
  },
  {
   "title": "Temperature (Top 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature DESC\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Temperature (Lowest 5)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\ndeviceName,\nTemperature\nfrom ATVsummary\nwhere timestamp > now() - interval 1 day\norder by temperature ASC\nlimit 5\n"
    }
   ]
  }
 ]
}