#!/system/bin/sh

initdir='/sdcard/initrom'

########## Init preparations ##########
wait_for_sdcard() {
    i=0
    while [ $i -lt 20 -a ! -d /sdcard/Download ]; do
        sleep 1
        i=`expr $i + 1`
    done
}

wait_for_sdcard

if [ ! -f $initdir ]; then
    mkdir -p $initdir
fi

if [ -d /data/data/org.mozilla.firefox/ ]; then
    # add worker to Denylist
    if [ ! -f $initdir/worker_settings_done ]; then
        i=0
        worker=10
        while [ $i -lt $worker ]; do
            magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES ('org.mozilla.firefox', 'org.mozilla.firefox:worker$i');"
            i=`expr $i + 1`
        done
        touch $initdir/worker_settings_done
        sleep 2
        reboot
    fi
fi

exit 0
